Use `importlib.metadata` instead of `pkg_resources` to get the package version.
This module was added to the Python in 3.8 (see [docs](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions)),
but a backport is available in the form of [`importlib-metadata`](https://pypi.org/project/importlib-metadata).

This avoids errors like

```console
$ uvx pypi-timemachine 2018-06-07
Traceback (most recent call last):
  File "/Users/erm/.cache/uv/archive-v0/FaS80efedkv1ufbNxv18X/bin/pypi-timemachine", line 6, in <module>
    from pypi_timemachine.core import main
  File "/Users/erm/.cache/uv/archive-v0/FaS80efedkv1ufbNxv18X/lib/python3.13/site-packages/pypi_timemachine/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
```

which FWIW has a simple workaround

```shell
uvx --with setuptools pypi-timemachine 2018-06-07
```